language: elixir

elixir: 1.10.2

otp_release: 22.0

stages:
  - test

env:
  global:
    - MIX_ENV=test

cache:
  directories:
    - deps

jobs:
  include:
    - stage: test
      script:
        - mix deps.get
        - mix test